=== mcdemarco/taminations/TAMination.dtd
<!--
    Copyright 2009 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!ELEMENT tamination (title?,definition?,styling?,timing?,comment?,(calllist|tam*))>

<!ELEMENT title ANY>
<!ATTLIST title  level CDATA #REQUIRED>

<!ELEMENT definition ANY>

<!ELEMENT timing ANY>

<!ELEMENT styling ANY>

<!ELEMENT comment ANY>

<!ELEMENT tam (path+,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #REQUIRED
              parts CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | Movement)* >
<!ATTLIST path numbers CDATA #IMPLIED >

<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT Movement EMPTY>
<!ATTLIST Movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT calllist (calldate*)>
<!ATTLIST calllist title CDATA #REQUIRED>
<!ELEMENT calldate (call+)>
<!ATTLIST calldate date CDATA #REQUIRED>
<!ELEMENT call EMPTY>
<!ATTLIST call name CDATA #REQUIRED
               href CDATA #REQUIRED>

=== mcdemarco/taminations/c1/switch_to_an_interlocked_diamond.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Switch to an Interlocked Diamond"
       from="Right-Hand Waves"
       formation="Formation girl 3 2 270  boy 1 2 90  boy -1 2 270  girl -3 2 90">
    <path numbers="7 2">
      <move select="Lead Right" scaleX="3" scaleY="3" beats="3" />
    </path>
    <path numbers="5 4">
      <move select="Run Right" />
    </path>
    <path numbers="3 6">
      <move select="Run Right" />
    </path>
    <path numbers="1 8">
      <move select="Lead Right" scaleY="3" beats="3" />
    </path>
  </tam>

  <tam title="Switch to an Interlocked Diamond"
       from="Left-Hand Waves"
       formation="Ocean Waves LH GBBG"
       parts="" >
    <path>
      <move select="Lead Left" scaleY="3" beats="3" />
    </path>
    <path>
      <move select="Run Left" />
    </path>
    <path>
      <move select="Run Left" />
    </path>
    <path>
      <move select="Lead Left" scaleX="3" scaleY="3" beats="3" />
    </path>
  </tam>

  <tam title="Switch to an Interlocked Diamond"
       from="Right-Hand Two-Faced Lines" formation="Two-Faced Lines RH">
    <path>
      <move select="Lead Right" scaleX="3" scaleY="3" beats="3" />
    </path>
    <path>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Lead Right" scaleY="3" beats="3" />
    </path>
  </tam>

  <tam title="Switch to an Interlocked Diamond"
       from="Left-Hand Two-Faced Lines" formation="Two-Faced Lines LH">
    <path>
      <move select="Lead Left" scaleY="3" beats="3" />
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Lead Left" scaleX="3" scaleY="3" beats="3" />
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/plus/three_quarters_tag_the_line.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="3/4 Tag the Line"
       from="Right-Hand Two-Faced Line"
       formation="Two-Faced Line RH"
       parts="" difficulty="1">
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Extend Left" beats="3" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tam title="3/4 Tag the Line"
       from="Left-Hand Two-Faced Line"
       formation="Two-Faced Line LH"
       parts="" difficulty="2">
    <path>
      <move select="Quarter Left" offsetX="-.5" offsetY=".5" />
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2.5" scaleY=".5" />
    </path>
    <path>
      <move select="Quarter Left" offsetX="-.5" offsetY=".5" />
      <move select="Extend Left" beats="3" scaleX="2.5" scaleY=".5" />
    </path>
  </tam>

  <tam title="3/4 Tag the Line"
       from="Right-Hand Wave"
       formation="Wave RH"
       parts="" difficulty="2">
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Extend Left" beats="3" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Quarter Left" offsetX="-.5" offsetY=".5" />
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2.5" scaleY=".5" />
    </path>
  </tam>

  <tam title="3/4 Tag the Line"
       from="Left-Hand Wave"
       formation="Wave LH"
       parts="" difficulty="1">
    <path>
      <move select="Quarter Left" offsetX="-.5" offsetY=".5" />
      <move select="Extend Left" beats="3" scaleX="2.5" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tam title="3/4 Tag the Line"
       from="Right-Hand Two-Faced Lines"
       formation="Two-Faced Lines RH"
       parts="" difficulty="1">
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Extend Left" beats="3" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Extend Left" beats="3" scaleX="3" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
      <move select="Extend Left" beats="3" scaleX="2" scaleY=".5" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/c3a/3_4_mix.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="3/4 Mix" from="Right-Hand Box" formation="Box RH" parts="4.5;4">
    <path>
      <move select="Cast Right"/>
      <move select="Dodge Right" beats="4"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Run Left" beats="4" scaleY="2"/>
    </path>
  </tam>

  <tam title="3/4 Mix" from="Right-Hand Waves" formation="Ocean Waves RH BGBG" parts="4.5;4">
    <path>
      <move select="Cast Right"/>
      <move select="Dodge Right" beats="4"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Run Left" beats="4" scaleY="2"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Dodge Right" beats="4"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Run Left" beats="4" scaleY="2"/>
    </path>
  </tam>

  <tam title="3/4 Mix" from="Right-Hand Columns" formation="Column RH GBGB" parts="4.5;3">
    <path>
      <move select="Hinge Right" scaleX=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Run Left"/>
    </path>
    <path>
      <move select="Hinge Right" scaleX=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Dodge Right" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
    </path>
    <path>
      <move select="Hinge Right" scaleX=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Run Left"/>
    </path>
    <path>
      <move select="Hinge Right" scaleX=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Dodge Right" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
    </path>
  </tam>

  <tam title="3/4 Mix" from="Right-Hand Diamonds" formation="Diamonds RH Girl Points" parts="4.5;4">
    <path>
      <move select="Cast Right"/>
      <move select="Run Right" beats="4" scaleY="2"/>
    </path>
    <path>
      <move select="Stand" beats="4.5"/>
      <move select="Dodge Right" beats="4"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Run Right" beats="4" scaleY="2"/>
    </path>
    <path>
      <move select="Stand" beats="4.5"/>
      <move select="Dodge Right" beats="4"/>
      <move select="Swing Right"/>
    </path>
  </tam>

  <tam title="3/4 Mix" from="Alamo Ring" formation="Alamo Wave" parts="4.5;4">
    <path>
      <move select="Sxtnth Left" />
      <move select="Cast Right"/>
      <move select="Dodge Right" beats="4" scaleY="1.25"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Sxtnth Right" />
      <move select="Cast Right"/>
      <move select="Run Left" beats="4" scaleY="2.25"/>
    </path>
    <path>
      <move select="Sxtnth Left" />
      <move select="Cast Right"/>
      <move select="Dodge Right" beats="4" scaleY="1.25"/>
      <move select="Swing Right"/>
    </path>
    <path>
      <move select="Sxtnth Right" />
      <move select="Cast Right"/>
      <move select="Run Left" beats="4" scaleY="2.25"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/ms/do_paso.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  
  
  

  <tam title="Do Paso"
       from="Static Square"
       formation="Static Square">
    <path>
      <move select="Quarter Right" />
      <move select="Extend Right" scaleY=".75" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".75" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="U-Turn Left" beats="3" offsetX="2" offsetY="-2.25" />
      <move select="Beau Wheel" scaleX=".75" scaleY=".75" />
      <move select="BackHinge Right" scaleY=".75" />
    </path>
    <path>
      <move select="Quarter Left" />
      <move select="Extend Right" scaleY=".75" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Lead Left" beats="2" scaleX="1.5" scaleY="1.75" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="3" scaleX=".25" scaleY="3" />
      <move select="Belle Wheel" scaleX=".75" scaleY=".75" />
      <move select="Hinge Left" scaleY=".75" />
    </path>
    <path>
      <move select="Quarter Right" />
      <move select="Extend Right" scaleY=".75" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".75" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="U-Turn Left" beats="3" offsetX="2" offsetY="-2.25" />
      <move select="Beau Wheel" scaleX=".75" scaleY=".75" />
      <move select="BackHinge Right" scaleY=".75" />
    </path>
    <path>
      <move select="Quarter Left" />
      <move select="Extend Right" scaleY=".75" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Lead Left" beats="2" scaleX="1.5" scaleY="1.75" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="3" scaleX=".25" scaleY="3" />
      <move select="Belle Wheel" scaleX=".75" scaleY=".75" />
      <move select="Hinge Left" scaleY=".75" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/c1/triangle_formation.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Outpoint Triangle Circulate"
       from="Left-Hand Diamonds"
       formation="Diamonds LH Girl Points"
       group=" ">
    <path numbers="6 3">
      <move select="Flip Left" />
    </path>
    <path numbers="2 7">
      <move select="Lead Left" beats="3" scaleY="3" />
    </path>
    <path numbers="5 4">
      <move select="Lead Left" beats="3" scaleX="3" />
    </path>
    <path numbers="8 1">
    </path>
  </tam>

  <tam title="Inpoint Triangle Circulate"
       from="Right-Hand Diamonds"
       formation="Formation boy 0 -3 270 girl -3 -2 90 boy 0 -1 270 girl 3 -2 270"
       group=" " >
    <path numbers="6 3">
      <move select="Run Right" beats="3" offsetX="-1" scaleY="1.5" />
    </path>
    <path numbers="2 7">
      <move select="Run Right" beats="3" offsetX="1" scaleY="1.5" />
    </path>
    <path numbers="5 4">
      <move select="Forward 2" beats="3"/>
    </path>
    <path numbers="8 1">
    </path>
  </tam>

  <tam title="Tandem-Based Triangle Circulate"
       from="Hourglass with Left-Hand Tandem Triangles"
       formation="Formation boy -2 -3 0 girl -3 0 90 boy -2 3 180 girl 0 1 0"
       group=" " >
    <path numbers="3 6">
      <move select="Forward 4" />
    </path>
    <path numbers="1 8">
    </path>
    <path numbers="2 7">
      <move select="U-Turn Left" beats="4" offsetX="-2" offsetY="2" />
    </path>
    <path numbers="4 5">
      <move select="U-Turn Left" beats="4" offsetX="2" offsetY="2" />
    </path>
  </tam>

  <tam title="Wave-Based Triangle Circulate"
       from="Right-Hand Galaxy"
       formation="Galaxy RH GP"
       group=" " >
    <path numbers="3 6">
      <move select="Lead Right" beats="3" scaleX="2" />
    </path>
    <path numbers="1 8">
      <move select="Lead Right" beats="3" scaleY="2" />
    </path>
    <path numbers="2 7">
      <move select="Flip Right" />
    </path>
    <path numbers="4 5">
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/c3a/trade_the_deucey.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  

  <tam title="Trade the Deucey"
       from="Normal Lines"
       formation="Normal Lines">
    <path>
      <move select="Forward" beats="1.5" />
      <move select="Extend Right" scaleX="3" scaleY="2" beats="4.5" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Flip Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Extend Left" scaleX="3" scaleY="2" beats="4.5" />
      <move select="Forward" beats="1.5" />
    </path>
  </tam>

  <tam title="Trade the Deucey"
       from="Lines Facing Out"
       formation="Lines Facing Out">
    <path>
      <move select="Run Left" scaleX="2" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Flip Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleX="3" scaleY="2" beats="6" />
    </path>
  </tam>

  <tam title="Trade the Deucey"
       from="Right-Hand Two-Faced Lines"
       formation="Two-Faced Lines RH">
    <path>
      <move select="Extend Right" scaleX="4" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
  </tam>

  <tam title="Trade the Deucey"
       from="Left-Hand Two-Faced Lines"
       formation="Two-Faced Lines LH">
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Extend Left" scaleX="4" scaleY="2" beats="6" />
    </path>
  </tam>

  <tam title="Trade the Deucey"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGGB">
    <path>
      <move select="Extend Right" scaleX="4" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleX="2" scaleY="2" beats="6" />
    </path>
  </tam>

  <tam title="Trade the Deucey"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGGB">
    <path>
      <move select="Run Left" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Run Right" scaleX="2" scaleY="2" beats="6" />
    </path>
    <path>
      <move select="Extend Left" scaleX="4" scaleY="2" beats="6" />
    </path>
  </tam>

  <!--tam title="Trade the Deucey"
       from="Right-Hand Diamonds"
       formation="Diamonds RH Girl Points">
    <path>
      <move select="Run Right" scaleY="1.25" beats="6" />
    </path>
    <path>
    </path>
    <path>
      <move select="Run Right" scaleY="1.25" beats="6" />
    </path>
    <path>
    </path>
  </tam-->


</tamination>

=== mcdemarco/taminations/c3a/eight_by_anything.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Eight by Swap Around" from="Lines" formation="Normal Lines" group=" ">
  <path>
    <move select="Extend Left" beats="2" scaleX="2" scaleY=".5"/>
    <move select="Lead Right" beats="3" scaleX="2.5" scaleY="2.5"/>
    <move select="Quarter Left" offsetX="1"/>
    <move select="Quarter Left"/>
    <move select="BackHinge Right" scaleY=".5"/>
    <move select="Quarter Left"/>
  </path>
  <path>
    <move select="Flip Right" offsetX="1"/>
  </path>
  <path>
    <move select="Forward 3"/>
  </path>
  <path>
    <move select="Extend Left" beats="2" scaleX="2" scaleY=".5"/>
    <move select="Lead Left" beats="4.5" scaleX="3.5" scaleY="2.5"/>
    <move select="Hinge Left" beats="3" scaleY=".5"/>
    <move select="Quarter Left"/>
  </path>
  </tam>

</tamination>

=== mcdemarco/taminations/c2/invert_the_column.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Invert the Column" from="Right-Hand Columns"
       formation="Column RH GBGB" parts="5;3;3">
    <path numbers="2 7">
      <move select="Run Left" offsetX="-1"/>
      <move select="Forward 2"/>
      <move select="Forward" beats="3"/>
      <move select="Forward" beats="3"/>
      <move select="Extend Left" beats="3" scaleY="2"/>
    </path>
    <path numbers="4 5">
      <move select="Forward" beats="5"/>
      <move select="Run Left" offsetX="-1"/>
      <move select="Forward" beats="3"/>
      <move select="Extend Left" beats="3" scaleY="2"/>
    </path>
    <path numbers="6 3">
      <move select="Forward" beats="5"/>
      <move select="Forward" beats="3"/>
      <move select="Run Left" offsetX="1"/>
      <move select="Extend Left" beats="3" scaleY="2"/>
    </path>
    <path numbers="8 1">
      <move select="Forward" beats="5"/>
      <move select="Forward" beats="3"/>
      <move select="Forward" beats="3"/>
      <move select="U-Turn Left" beats="3" offsetX="3"/>
    </path>
  </tam>


</tamination>
