=== mcdemarco/taminations/TAMination.dtd
<!--
    Copyright 2009 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!ELEMENT tamination (title?,definition?,styling?,timing?,comment?,(calllist|tam*))>

<!ELEMENT title ANY>
<!ATTLIST title  level CDATA #REQUIRED>

<!ELEMENT definition ANY>

<!ELEMENT timing ANY>

<!ELEMENT styling ANY>

<!ELEMENT comment ANY>

<!ELEMENT tam (path+,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #REQUIRED
              parts CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | Movement)* >
<!ATTLIST path numbers CDATA #IMPLIED >

<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT Movement EMPTY>
<!ATTLIST Movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT calllist (calldate*)>
<!ATTLIST calllist title CDATA #REQUIRED>
<!ELEMENT calldate (call+)>
<!ATTLIST calldate date CDATA #REQUIRED>
<!ELEMENT call EMPTY>
<!ATTLIST call name CDATA #REQUIRED
               href CDATA #REQUIRED>

=== mcdemarco/taminations/c1/anything_and_weave.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="And Weave" from="Right-Hand Box"
       formation="Formation boy 1 2 270 girl -1 2 90">
    <path numbers="3 2">
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Left" scaleY=".5" />
    </path>
    <path numbers="1 4">
      <move select="Lead Right" />
    </path>
  </tam>

  <tam title="And Weave" from="Single Eight Chain Thru"
       formation="Formation boy 0 3 270 girl 0 1 90">
    <path numbers="1 4">
      <move select="Extend Left" scaleY=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Left"  />
    </path>
    <path numbers="2 3">
      <move select="Extend Left" scaleY=".5"/>
      <move select="Lead Right" scaleY=".5" />
    </path>
  </tam>

  <tam title="And Weave"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGGB"
       parts="" >
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Left" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" />
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Left" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" />
    </path>
  </tam>

  <tam title="And Weave"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGGB"
       parts="" >
    <path>
      <move select="Lead Left" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Right" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Left" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Right" scaleY=".5" />
    </path>
  </tam>

  <tam title="And Weave"
       from="Right-Hand Columns"
       formation="Column RH GBGB"
       parts="" >
    <path>
      <move select="Lead Right" scaleX=".5" />
    </path>
    <path>
      <move select="Extend Right" beats="1.5" scaleY="1.5" />
      <move select="Hinge Left" scaleX=".5" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Right" scaleX=".5" />
    </path>
    <path>
      <move select="Extend Right" beats="1.5" scaleY="1.5" />
      <move select="Hinge Left" scaleX=".5" scaleY=".5" />
    </path>
  </tam>

  <tam title="And Weave"
       from="Left-Hand Columns"
       formation="Column LH GBGB"
       parts="" >
    <path>
      <move select="Extend Left" beats="1.5" scaleY="1.5" />
      <move select="Hinge Right" scaleX=".5" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Left" scaleX=".5" />
    </path>
    <path>
      <move select="Extend Left" beats="1.5" scaleY="1.5" />
      <move select="Hinge Right" scaleX=".5" scaleY=".5" />
    </path>
    <path>
      <move select="Lead Left" scaleX=".5" />
    </path>
  </tam>

  <tam title="And Weave"
       from="Eight Chain Thru"
       formation="Eight Chain Thru"
       parts="" >
    <path>
      <move select="Extend Left" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
      <move select="Hinge Left" scaleY=".5" />
    </path>
    <path>
      <move select="Forward" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
      <move select="Hinge Left" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Left" />
      <move select="Quarter Right" offsetX="1" />
    </path>
    <path>
      <move select="Forward" />
      <move select="Lead Right" />
    </path>
  </tam>

  <tam title="As Couples And Weave"
       from="Two-Faced Lines"
       formation="Two-Faced Lines RH"
       parts="" >
    <path>
      <move select="Extend Right" hands="right" beats="3" scaleX="2" scaleY="3.5" />
      <move select="Lead Left" hands="both" beats="2" scaleX=".5" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Right" hands="left" beats="3" scaleX="2" scaleY="2.5" />
      <move select="Lead Left" hands="left" beats="2" scaleX="1.5" scaleY="1.5" />
    </path>
    <path>
      <move select="Lead Right" hands="left" beats="2" scaleX=".5" />
    </path>
    <path>
      <move select="Lead Right" hands="right" beats="2" scaleX="1.5" scaleY="3" />
    </path>
  </tam>

  <tam title="All 8 And Weave"
       from="Mini Waves"
       formation="Static MiniWaves RH"
       parts="" >
    <path>
      <move select="Extend Right" beats="3" scaleX="3" scaleY="2" />
      <move select="Hinge Left" />
    </path>
    <path>
      <move select="Quarter Right" beats="2" offsetY="-1" />
    </path>
    <path>
      <move select="Extend Right" beats="3" scaleX="3" scaleY="2" />
      <move select="Hinge Left" />
    </path>
    <path>
      <move select="Quarter Right" beats="2" offsetY="-1" />
    </path>
  </tam>


</tamination>

=== mcdemarco/taminations/adv/cross_over_circulate.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Cross Over Circulate"
       from="Right-Hand Two-Faced Lines"
       formation="Two-Faced Lines RH"
       parts="3" >
    <path numbers="1 8">
      <move select="Extend Right" beats="3" scaleX="1.5" />
      <move select="Extend Right" beats="3" scaleX="2.5" />
    </path>
    <path numbers="2 7">
      <move select="Extend Left" beats="3" scaleX="2.5" />
      <move select="Extend Left" beats="3" scaleX="1.5" />
    </path>
    <path numbers="3 6">
      <move select="Quarter Right" offsetX=".1" offsetY="-1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Right" offsetX="1" offsetY="-.1" />
    </path>
    <path numbers="4 5">
      <move select="Quarter Right" offsetX=".1" offsetY="-1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Right" offsetX="1" offsetY="-.1" />
    </path>
  </tam>

  <tam title="Cross Over Circulate"
       from="Left-Hand Two-Faced Lines"
       formation="Two-Faced Lines LH"
       parts="3" >
    <path numbers="1 8">
      <move select="Quarter Left" offsetX=".1" offsetY="1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Left" offsetX="1" offsetY=".1" />
    </path>
    <path numbers="2 7">
      <move select="Quarter Left" offsetX=".1" offsetY="1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Left" offsetX="1" offsetY=".1" />
    </path>
    <path numbers="3 6">
      <move select="Extend Right" beats="3" scaleX="1.5" />
      <move select="Extend Right" beats="3" scaleX="2.5" />
    </path>
    <path numbers="4 5">
      <move select="Extend Left" beats="3" scaleX="2.5" />
      <move select="Extend Left" beats="3" scaleX="1.5" />
    </path>
  </tam>

  <tam title="Cross Over Circulate"
       from="Lines Facing Out"
       formation="Lines Facing Out"
       parts="3" >
    <path>
      <move select="Quarter Left" offsetX=".1" offsetY="1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Left" offsetX="1" offsetY=".1" />
    </path>
    <path>
      <move select="Quarter Left" offsetX=".1" offsetY="1" />
      <move select="Forward 2" beats="3" />
      <move select="Quarter Left" offsetX="1" offsetY=".1" />
    </path>
    <path>
      <move select="Lead Right" />
      <move select="Forward 2" beats="3" />
      <move select="Lead Right" />
    </path>
    <path>
      <move select="Lead Right" />
      <move select="Forward 2" beats="3" />
      <move select="Lead Right" />
    </path>
  </tam>

  <tam title="Cross Over Circulate"
       from="Inverted Lines"
       formation="Inverted Lines Centers In"
       parts="" >
    <path>
      <move select="Flip Left" beats="6" scaleY="2" />
    </path>
    <path>
      <move select="Extend Left" beats="4.5" scaleX="3" scaleY="2" />
      <move select="Forward" beats="1.5" />
    </path>
    <path>
      <move select="Forward" beats="1.5" />
      <move select="Extend Right" beats="4.5" scaleX="3" scaleY="2" />
    </path>
    <path>
      <move select="Run Right" beats="6" scaleY="2" />
    </path>
  </tam>

  <tam title="Cross Over Circulate"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGBG"
       parts="3" >
    <path numbers="1 8">
      <move select="Forward" beats="1.5" />
      <move select="Extend Right" beats="4.5" scaleX="3" scaleY="2" />
    </path>
    <path numbers="2 7">
      <move select="Run Left" beats="6" scaleX=".5" scaleY="2" />
    </path>
    <path numbers="3 6">
      <move select="Forward" beats="1.5" />
      <move select="Extend Right" beats="4.5" scaleX="3" scaleY="2" />
    </path>
    <path numbers="4 5">
      <move select="Run Right" beats="6" scaleX="1.5" scaleY="2" />
    </path>
  </tam>

  <tam title="Cross Over Circulate"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGBG"
       parts="3" >
    <path>
      <move select="Run Left" beats="6" scaleX=".5" scaleY="2" />
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="2.5" scaleY="2" />
      <move select="Forward" scaleX="1.5" beats="2" />
    </path>
    <path>
      <move select="Run Right" beats="6" scaleX="1.5" scaleY="2" />
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="2.5" scaleY="2" />
      <move select="Forward" scaleX="1.5" beats="2" />
    </path>
  </tam>

  <tam title="Cross Over Circulate" from="T-Bones 1"
       formation="T-Bone DLRD" >
    <path>
      <move select="Run Left" beats="5" scaleY="2" />
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Dodge Left"/>
    </path>
    <path>
      <move select="Dodge Right"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Run Right" beats="5" scaleX="2" scaleY="2" />
    </path>
  </tam>

  <tam title="Cross Over Circulate" from="T-Bones 2"
       formation="T-Bone ULRU" >
    <path>
      <move select="Dodge Right"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Dodge Left"/>
    </path>
    <path>
      <move select="Dodge Right"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Dodge Left"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/c3a/team_up.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  

  <tam title="Team Up" from="Completed Double Pass Thru" formation="Completed Double Pass Thru">
    <path>
      <move select="Quarter Left" offsetY="1"/>
      <move select="Quarter Right" beats="1.5" hands="right" offsetX="1"/>
    </path>
    <path>
      <move select="Lead Right"/>
      <move select="Hinge Right"/>
    </path>
    <path>
      <move select="Dodge Left"/>
    </path>
    <path>
      <move select="Run Right"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/adv/any_hand_concept.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Any Hand Remake" parts="1.5;3"
  formation="Formation boy 3 2 270  girl 1 2 90  boy -1 2 90  girl -3 2 270"
  group="Any Hand">
    <path numbers="3 6">
      <move select="Hinge Right"/>
      <move select="Flip Left"/>
      <move select="Hinge Right" scaleX="2" scaleY="2" offsetX=".33" offsetY=".33" />
      <move select="Hinge Right" scaleX="2" scaleY="2" offsetX="-.33" offsetY=".33" />
      <move select="Hinge Right" scaleX="2" scaleY="2" offsetX="-.33" offsetY="-.33" />
    </path>
    <path numbers="1 8">
      <move select="Hinge Right"/>
      <move select="Stand" beats="3"/>
      <move select="Quarter Left" hands="right" offsetX=".33" offsetY="-.33" />
      <move select="Quarter Left" hands="right" offsetX="-.33" offsetY="-.33" />
      <move select="Quarter Left" hands="right" offsetX="-.33" offsetY=".33" />
    </path>
    <path numbers="7 2">
      <move select="Hinge Left"/>
      <move select="Stand" beats="3"/>
      <move select="Quarter Right" hands="left" offsetX=".33" offsetY=".33" />
      <move select="Quarter Right" hands="left" offsetX="-.33" offsetY=".33" />
      <move select="Quarter Right" hands="left" offsetX="-.33" offsetY="-.33" />
    </path>
    <path numbers="5 4">
      <move select="Hinge Left"/>
      <move select="Run Right"/>
      <move select="Hinge Left" scaleX="2" scaleY="2" offsetX=".33" offsetY="-.33" />
      <move select="Hinge Left" scaleX="2" scaleY="2" offsetX="-.33" offsetY="-.33" />
      <move select="Hinge Left" scaleX="2" scaleY="2" offsetX="-.33" offsetY=".33" />
    </path>
  </tam>

  <tam title="Any Hand Quarter Thru"
      formation="Formation boy 3 2 90  girl 1 2 270  boy -1 2 270  girl -3 2 90"
      group="Any Hand">
    <path numbers="7 2">
      <move select="Hinge Left"/>
    </path>
    <path numbers="5 4">
      <move select="Hinge Left"/>
      <move select="Run Right"/>
    </path>
    <path numbers="3 6">
      <move select="Hinge Right"/>
      <move select="Flip Left"/>
    </path>
    <path numbers="1 8">
      <move select="Hinge Right"/>
    </path>
  </tam>

  <tam title="Any Hand Swing Thru" formation="Inverted Lines Centers In" group="Any Hand">
    <path numbers="5 4">
      <move select="Swing Left"/>
      <move select="Run Right"/>
    </path>
    <path numbers="6 3">
      <move select="Swing Left"/>
    </path>
    <path numbers="7 2">
      <move select="Swing Right"/>
    </path>
    <path numbers="8 1">
      <move select="Swing Right"/>
      <move select="Flip Left"/>
    </path>
  </tam>

  <tam title="Any Hand Three Quarter Thru" formation="Inverted Lines Centers In" group="Any Hand">
    <path>
      <move select="Cast Left"/>
      <move select="Run Right"/>
    </path>
    <path>
      <move select="Cast Left"/>
    </path>
    <path>
      <move select="Cast Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Flip Left"/>
    </path>
  </tam>

  <tam title="Any Hand Three Quarter Thru (from a diamond)"
       formation="Diamond RH" group="Any Hand">
    <path numbers="2 3">
      <move select="Stand" beats="4.5"/>
      <move select="Run Right"/>
    </path>
    <path numbers="4 1">
      <move select="Cast Right"/>
      <move select="Flip Left"/>
    </path>
  </tam>

  <tam title="Any Hand Three Quarter Thru (from twin diamonds)"
       formation="Diamonds RH Girl Points" group="Any Hand">
    <path>
      <move select="Cast Right"/>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Stand" beats="4.5"/>
      <move select="Run Right"/>
    </path>
    <path>
      <move select="Cast Right"/>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Stand" beats="4.5"/>
      <move select="Run Right"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/plus/spin_chain_the_gears.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Spin Chain the Gears"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGGB"
       parts="3;4.5;3;4.5;3" difficulty="1">
    <path>
      <move select="Swing Right" />
      <move select="Cast Left" />
      <move select="Swing Right" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Flip Right" />
    </path>
    <path>
      <move select="Swing Right" />
      <move select="Stand" beats="2" />
      <move select="Flip Right" beats="5.5" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Swing Right" />
      <move select="Cast Left" />
    </path>
    <path>
      <move select="Swing Right" />
      <move select="Stand" beats="2" />
      <move select="Flip Right" beats="5.5" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Stand" beats="3" />
      <move select="Cast Left" />
    </path>
    <path>
      <move select="Swing Right" />
      <move select="Cast Left" />
      <move select="Stand" beats="3" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Flip Right" />
    </path>
  </tam>

  <tam title="Spin Chain the Gears"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGGB"
       parts="3;4.5;3;4.5;3" difficulty="2">
    <path>
      <move select="Swing Left" />
      <move select="Cast Right" />
      <move select="Stand" beats="3" />
      <move select="Cast Right" hands="gripright"/>
      <move select="Flip Left" />
    </path>
    <path>
      <move select="Swing Left" />
      <move select="Stand" beats="2" />
      <move select="Flip Left" beats="5.5" />
      <move select="Cast Right" hands="gripright"/>
      <move select="Stand" beats="3" />
      <move select="Cast Right" />
    </path>
    <path>
      <move select="Swing Left" />
      <move select="Stand" beats="2" />
      <move select="Flip Left" beats="5.5" />
      <move select="Cast Right" hands="gripright"/>
      <move select="Swing Left" />
      <move select="Cast Right" />
    </path>
    <path>
      <move select="Swing Left" />
      <move select="Cast Right" />
      <move select="Swing Left" />
      <move select="Cast Right" hands="gripright"/>
      <move select="Flip Left" />
    </path>
  </tam>

  <tam title="Spin Chain the Gears"
       from="Tidal Wave"
       formation="Tidal Wave RH BGGB"
       parts="3;4.5;3;4.5;3" difficulty="3">
    <path>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Swing Left" scaleX=".5" scaleY=".5"/>
      <move select="Hinge Left" scaleY=".5"/>
      <move select="Stand" beats="3" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Swing Right"/>
      <move select="Cast Left"/>
    </path>
    <path>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Flip Right" beats="4.5" scaleY=".25"/>
      <move select="Stand" beats="3" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Flip Right" beats="4.5" scaleY=".25"/>
      <move select="Swing Right"/>
      <move select="Cast Left" hands="gripleft"/>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Swing Right" scaleX=".5" scaleY=".5"/>
      <move select="Swing Left" scaleX=".5" scaleY=".5"/>
      <move select="Hinge Left" scaleY=".5"/>
      <move select="Stand" beats="3" />
      <move select="Cast Left" hands="gripleft"/>
      <move select="Stand" beats="3"/>
      <move select="Cast Left"/>
    </path>
  </tam>

  <tam title="Spin Chain the Gears"
       from="Two-Faced Lines"
       formation="Two-Faced Lines RH"
       parts="3;4.5;3;4.5;3" difficulty="3">
    <path>
      <move select="Run Right"/>
      <move select="Cast Left"/>
      <move select="Swing Right"/>
      <move select="Hinge Left" scaleX=".5"/>
      <move select="Hinge Left" scaleX=".5" scaleY=".5"/>
      <move select="Hinge Left"  scaleY=".5"/>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Flip Left"/>
      <move select="Stand" beats="3"/>
      <move select="Flip Left" beats="4.5"/>
      <move select="Lead Right" scaleX="1.5"/>
      <move select="Lead Right" scaleX="1.5" scaleY="1.5"/>
      <move select="Lead Right"  scaleY="1.5"/>
      <move select="Stand" beats="3"/>
      <move select="Cast Right" hands="gripright"/>
    </path>
    <path>
      <move select="Flip Left"/>
      <move select="Stand" beats="3"/>
      <move select="Flip Left" beats="4.5"/>
      <move select="Lead Right" scaleX="1.5"/>
      <move select="Lead Right" scaleX="1.5" scaleY="1.5"/>
      <move select="Lead Right"  scaleY="1.5"/>
      <move select="Swing Left"/>
      <move select="Cast Right" hands="gripright"/>
    </path>
    <path>
      <move select="Run Right"/>
      <move select="Cast Left"/>
      <move select="Stand" beats="3"/>
      <move select="Hinge Left" scaleX=".5"/>
      <move select="Hinge Left" scaleX=".5" scaleY=".5"/>
      <move select="Hinge Left" scaleY=".5"/>
      <move select="Flip Right"/>
    </path>
  </tam>


</tamination>

=== mcdemarco/taminations/c3a/link_up.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  

  <tam title="Link Up" from="Two-Faced Lines" formation="Two-Faced Lines RH" parts="2">
    <path>
      <move select="Forward 2" hands="right"/>
      <move select="Run Right" beats="5" offsetX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Forward 2" hands="left"/>
      <move select="Swing Right"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Lead Left" beats="2" hands="left" scaleX="2" scaleY="2"/>
      <move select="Quarter Left"/>
      <move select="Forward 2" beats="3.5"/>
    </path>
    <path>
      <move select="Quarter Left" beats="2" hands="left"/>
      <move select="Quarter Left"/>
      <move select="Forward 4" beats="3.5"/>
    </path>
  </tam>

</tamination>
