=== mcdemarco/taminations/TAMination.dtd
<!--
    Copyright 2009 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!ELEMENT tamination (title?,definition?,styling?,timing?,comment?,(calllist|tam*))>

<!ELEMENT title ANY>
<!ATTLIST title  level CDATA #REQUIRED>

<!ELEMENT definition ANY>

<!ELEMENT timing ANY>

<!ELEMENT styling ANY>

<!ELEMENT comment ANY>

<!ELEMENT tam (path+,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #REQUIRED
              parts CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | Movement)* >
<!ATTLIST path numbers CDATA #IMPLIED >

<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT Movement EMPTY>
<!ATTLIST Movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT calllist (calldate*)>
<!ATTLIST calllist title CDATA #REQUIRED>
<!ELEMENT calldate (call+)>
<!ATTLIST calldate date CDATA #REQUIRED>
<!ELEMENT call EMPTY>
<!ATTLIST call name CDATA #REQUIRED
               href CDATA #REQUIRED>

=== mcdemarco/taminations/plus/extend.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Extend" from="Right-Hand Wave" formation="Wave RH" difficulty="1">
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Forward 2"/>
    </path>
  </tam>

  <tam title="Extend"
       from="Right-Hand 1/4 Tag"
       formation="Quarter Tag"
       parts="" difficulty="1">
    <path>
      <move select="Extend Left" scaleY="2" beats="2" />
    </path>
    <path>
      <move select="Forward" beats="2" />
    </path>
    <path>
      <move select="Forward 2" />
    </path>
    <path>
      <move select="Forward 2" />
    </path>
  </tam>

  <tam title="Extend"
       from="Left-Hand 1/4 Tag"
       formation="Quarter Tag LH"
       parts="" difficulty="2">
    <path>
      <move select="Forward" beats="2" />
    </path>
    <path>
      <move select="Extend Right" scaleY="2" beats="2" />
    </path>
    <path>
      <move select="Forward 2" />
    </path>
    <path>
      <move select="Forward 2" />
    </path>
  </tam>

  <tam title="Extend"
       from="Double Pass Thru"
       formation="Double Pass Thru"
       parts="" difficulty="1">
    <path>
    </path>
    <path>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleY="2" />
    </path>
    <path>
      <move select="Forward" beats="2" />
    </path>
  </tam>

  <tam title="Extend"
       from="Ocean Waves"
       formation="Ocean Waves RH BGGB"
       parts="" difficulty="1">
    <path>
      <move select="Forward 2" />
    </path>
    <path>
      <move select="Forward" />
    </path>
    <path>
      <move select="Forward 2" />
    </path>
    <path>
      <move select="Extend Right" scaleY="2" beats="2" />
    </path>
  </tam>

  <tam title="Extend"
       from="3/4 Tag"
       formation="3/4 Tag"
       parts="" difficulty="1">
    <path>
    </path>
    <path>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleY="2" />
    </path>
    <path>
      <move select="Forward" beats="2" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/c1/switch_to_an_hourglass.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  

  <tam title="Switch to an Hourglass" from="Right-Hand Two-Faced Lines"
       formation="Two-Faced Lines RH">
    <path>
      <move select="Extend Right" beats="4" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Flip Left" beats="4"/>
    </path>
    <path>
      <move select="Flip Left" beats="4"/>
    </path>
    <path>
      <move select="Lead Right" beats="2"/>
      <move select="Forward 2"/>
    </path>

  </tam>

  <tam title="Switch to an Hourglass" from="Left-Hand Two-Faced Lines"
       formation="Two-Faced Lines LH">
    <path>
      <move select="Lead Left" beats="2"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Flip Right" beats="4"/>
    </path>
    <path>
      <move select="Flip Right" beats="4"/>
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="2" scaleY="2"/>
    </path>
  </tam>

  <tam title="Switch to an Hourglass" from="3 and 1 Lines"
       formation="Formation boy -2 3 180 girl -2 1 180 boy -2 -1 180 girl -2 -3 0">
    <path>
      <move select="Lead Left" beats="2"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Flip Right" beats="4"/>
    </path>
    <path>
      <move select="Run Left" beats="4"/>
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="2" scaleY="2"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/c2/3_by_1_transfer_the_column.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  

  <tam title="3 By 1 Transfer the Column"
       from="Right-Hand Columns"
       formation="Formation girl -3 -1 180 boy 1 -1 180 girl -1 -1 180 boy 3 -1 180"
       parts="" >
    <path>
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Right" beats="2.5" scaleX="2" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward 2" />
      <move select="Run Right" beats="4" scaleY="2" offsetX="1" />
      <move select="Lead Right" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Lead Right" beats="4.5" scaleX="4" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward" />
      <move select="Cast Right" />
      <move select="Forward 2" />
    </path>
  </tam>

  <tam title="3 By 1 Transfer the Column"
       from="Left-Hand Columns"
       formation="Formation girl 3 -1 0 boy -1 -1 0 girl 1 -1 0 boy -3 -1 0"
       parts="" >
    <path>
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Left" beats="2.5" scaleX="2" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward 2" />
      <move select="Run Left" beats="4" scaleY="2" offsetX="1" />
      <move select="Lead Left" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Lead Left" beats="4.5" scaleX="4" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward" />
      <move select="Cast Left" />
      <move select="Forward 2" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/c2/cross_back.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Cross Back"
       from="Right-Hand Box"
       formation="Box RH" >
    <path numbers="1 4">
      <move select="Extend Right" hands="left" beats="2" scaleX="3" scaleY="2" />
      <move select="Forward" />
    </path>
    <path numbers="2 3">
      <move select="U-Turn Right" />
    </path>
  </tam>

  <tam title="Cross Back"
       from="Left-Hand Box"
       formation="Box LH" >
    <path numbers="1 4">
      <move select="U-Turn Left" />
    </path>
    <path numbers="2 3">
      <move select="Extend Left" hands="right" beats="2" scaleX="3" scaleY="2" />
      <move select="Forward" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/ms/turn_thru.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>
  
  
  
  

  <tam title="Turn Thru"
       from="Facing Couples"
       formation="Facing Couples"
       parts="" >
    <path>
      <move select="Extend Left" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Left" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tam title="Turn Thru"
       from="Lines"
       formation="Normal Lines"
       parts="" >
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".5" />
      <move select="Swing Right" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tam title="Turn Thru"
       from="Ocean Waves"
       formation="Ocean Waves RH BGGB"
       parts="" >
    <path>
      <move select="Hinge Right" scaleX=".75" />
      <move select="Hinge Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" scaleY=".25" />
    </path>
    <path>
      <move select="Hinge Right" scaleX=".75" />
      <move select="Hinge Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Right" beats="2" scaleY="1.75" />
    </path>
    <path>
      <move select="Hinge Right" scaleX=".75" />
      <move select="Hinge Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Right" beats="2" scaleY="1.75" />
    </path>
    <path>
      <move select="Hinge Right" scaleX=".75" />
      <move select="Hinge Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" scaleY=".25" />
    </path>
  </tam>
</tamination>

=== mcdemarco/taminations/c1/ah_so.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Ah So" from="Right-Hand Wave" formation="Wave RH">
    <path numbers="1 4">
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="2" />
    </path>
    <path numbers="2 3">
      <move select="U-Turn Right" hands="gripright" offsetX="-2" />
    </path>
  </tam>

  <tam title="Ah So" from="Left-Hand Wave" formation="Wave LH">
    <path>
      <move select="Run Left" hands="gripleft" scaleY="2" offsetX="2" />
    </path>
    <path>
      <move select="U-Turn Left" hands="gripleft" offsetX="-2" />
    </path>
  </tam>

  <tam title="Ah So"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGGB">
    <path>
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-1" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-1" />
    </path>
    <path>
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="1" />
    </path>
  </tam>

  <tam title="Ah So"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGGB"
       parts="" >
    <path>
      <move select="Run Left" hands="gripleft" scaleY="2" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Left" hands="gripleft" offsetX="-1" />
    </path>
    <path>
      <move select="U-Turn Left" hands="gripleft" offsetX="-1" />
    </path>
    <path>
      <move select="Run Left" hands="gripleft" scaleY="2" offsetX="1" />
    </path>
  </tam>

  <tam title="Ah So"
       from="Inverted Lines"
       formation="Inverted Lines Centers In"
       parts="" >
    <path>
      <move select="Run Left" hands="gripleft" scaleY="2" offsetX="-1" />
    </path>
    <path>
      <move select="U-Turn Left" hands="gripleft" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-1" />
    </path>
    <path>
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="1" />
    </path>
  </tam>

  <tam title="Ah So" from="3 and 1 Lines"
       formation="Formation girl -2 3 180 boy -2 1 0 girl -2 -1 180 boy -2 -3 180">
    <path numbers="5 4">
      <move select="Run Left" beats="4" hands="left" scaleY="2" offsetX="-1" />
    </path>
    <path numbers="6 3">
      <move select="U-Turn Left" beats="4" hands="left" offsetX="1" />
    </path>
    <path numbers="7 2">
      <move select="U-Turn Right" beats="4" hands="left" offsetX="1" />
    </path>
    <path numbers="8 1">
      <move select="Run Right" beats="4" hands="right" scaleX="2" scaleY="2" offsetX="1" />
    </path>
  </tam>


  <tam title="As Couples Ah So"
       from="Two-Faced Tidal Line"
       formation="Two-Faced Tidal Line RH"
       parts="" group=" ">
    <path>
      <move select="Run Right" beats="5" hands="gripright" scaleX="2" scaleY="3" offsetX="2" offsetY="-.5" />
    </path>
    <path>
      <move select="Run Right" beats="5" hands="gripboth" offsetX="2" offsetY=".5" scaleY="2" />
    </path>
    <path>
      <move select="U-Turn Right" beats="5" hands="gripboth" offsetX="-2" offsetY=".5" />
    </path>
    <path>
      <move select="Run Right" beats="5" hands="gripright" scaleY="3" offsetX="-2" offsetY="3.5" />
    </path>
  </tam>

  <tam title="Concentric Ah So" from="Tidal Wave" formation="Tidal Wave RH BGGB" group=" ">
    <path>
      <move select="Run Right" hands="gripright" offsetX="3" scaleY="2.25"/>
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-3" offsetY="1.5"/>
    </path>
    <path>
      <move select="Run Right" hands="gripright" scaleY="1.25" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-1" offsetY="-.5"/>
    </path>
  </tam>

  <tam title="Stretch Ah So" from="Right-Hand Waves" formation="Ocean Waves RH BGGB" group=" ">
    <path>
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="3" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-3" />
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" offsetX="-1" />
    </path>
    <path>
      <move select="Run Right" hands="gripright" scaleY="2" offsetX="1" />
    </path>
  </tam>

  <tam title="Tandem Ah So" from="Right-Hand Waves" formation="Ocean Waves RH BGGB" group=" ">
    <path>
      <move select="Quarter Right" hands="gripright" beats="4" offsetX="4"/>
      <move select="Quarter Right" hands="gripright" beats="4" offsetX="4" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Right" hands="gripright" beats="4" offsetX="-3" offsetY="-2"/>
      <move select="Quarter Right" hands="gripright" beats="4" offsetX="-2" offsetY="-2"/>
    </path>
    <path>
      <move select="U-Turn Right" hands="gripright" beats="8" offsetX="1"/>
    </path>
    <path>
      <move select="Run Right" hands="gripright" beats="8" offsetX="-1" scaleY="2"/>
    </path>
  </tam>


</tamination>

=== mcdemarco/taminations/c3a/bias_circulate.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>



  <tam title="Bias Circulate" from="Right-Hand Waves" formation="Ocean Waves RH BGBG">
    <path>
      <move select="Extend Right" beats="3" scaleX="2" scaleY="2"/>
      <move select="Hinge Right"/>
      <move select="Lead Left" beats="3"/>
    </path>
    <path>
      <move select="Run Left" beats="7.5"/>
    </path>
    <path>
      <move select="Lead Left" beats="3"/>
      <move select="Hinge Right"/>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Run Right" beats="7.5" scaleX="2" scaleY="3"/>
    </path>
  </tam>

  <tam title="Bias Circulate" from="Left-Hand Waves" formation="Ocean Waves LH BGBG">
    <path>
      <move select="Run Left" beats="7.5" scaleX="2" scaleY="3"/>
    </path>
    <path>
      <move select="Lead Right" beats="3"/>
      <move select="Hinge Left"/>
      <move select="Extend Right" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Run Right" beats="7.5"/>
    </path>
    <path>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
      <move select="Hinge Left"/>
      <move select="Lead Right" beats="3"/>
    </path>
  </tam>

</tamination>

=== mcdemarco/taminations/c2/exchange_the_diamond.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "../tamination.dtd">
<!--

    Copyright 2012 Brad Christie

    This file is part of TAMinations.

    TAMinations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TAMinations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with TAMinations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination>

  <tam title="Exchange the Diamond"
       from="Right-Hand Diamonds"
       formation="Diamonds RH Girl Points"
       parts="3;3;3" >
    <path numbers="6 3">
      <move select="Lead Right" beats="3" scaleX="2" />
      <move select="Lead Right" beats="3" scaleY="2" />
      <move select="Lead Left" beats="3" scaleX="3" scaleY="3" />
      <move select="Lead Left" beats="3" scaleY="3" />
    </path>
    <path numbers="2 7">
      <move select="Lead Right" beats="3" scaleY="3" ></move>
      <move select="Lead Left" beats="3" scaleX="3" scaleY="3" />
      <move select="Lead Left" beats="3" scaleY="3" />
      <move select="Lead Left" beats="3" scaleX="3" />
    </path>
    <path numbers="5 4">
      <move select="Lead Left" beats="3" scaleX="3" scaleY="3" />
      <move select="Lead Left" beats="3" scaleY="3" />
      <move select="Lead Left" beats="3" scaleX="3" />
      <move select="Lead Left" beats="3" scaleY="3" />
    </path>
    <path numbers="8 1">
    	<move select="Lead Right" beats="3" scaleY="3" />
    	<move select="Lead Right" beats="3" scaleX="2" />
    	<move select="Lead Right" beats="3" scaleY="2" />
    	<move select="Lead Left" beats="3" scaleX="3" scaleY="3" />
    </path>
  </tam>
</tamination>
